### ISSUE TITLE
Scrape maximum number of reviews

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#13]
Following the latest `develop` branch, this package scrapes the number of reviews based on the given parameter, for instance: `rotten-reviews doctor_who/s11 10 --tv` scrapes 10 reviews on the TV series Doctor Who: Season 10. As of this time of writing, the page has only ~360 reviews (18 pages). And if attempting to fetch more than the available reviews, this will happen:

```console
$ rotten-reviews doctor_who/s11 500 --tv
⚠️  Page not found for 'doctor_who/s11'. You can check the page manually by opening this link:
https://www.rottentomatoes.com/doctor_who/s11/1/reviews/?page=undefined&type=user&sort=

```

This is caused by the part of the code where it calculates the number of pages needed to fetch the given number of reviews:

https://github.com/grikomsn/rotten-reviews/blob/6e3ca0f205933b2dbff9b13cf5c32d2e39dfb095/index.js#L9-L18

Here I'm proposing to add a logic where it fetches the first page to scrape the number of available pages, then limits the number of requests for fetching the pages. If anyone would like to work on this, do send a PR and I'll help you along the way. ✨

**Comment by hitechcrafters** [comment]
Hi @grikomsn. I'll try to ix it :)

**Comment by hitechcrafters** [comment]
@grikomsn isn't this fixed here https://github.com/grikomsn/rotten-reviews/pull/12 ?

**Comment by grikomsn** [comment]
PR #12 is for merging `develop` to `master` when all related issues and PRs are resolved.

What I meant about this issue is handling the error when trying to fetch the number of reviews that exceeds the available reviews.
