### ISSUE TITLE
Change payload structure

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#14]
The result of running the package is straightforward, which gives the desired number of reviews, like below:

```console
$ rotten-reviews doctor_who/s11 3 --tv
[
  {
    "reviewer": "Frank E.",
    "date": "",
    "stars": 0,
    "review": ""
  },
  {
    "reviewer": "Shannon S",
    "date": "",
    "stars": 5,
    "review": ""
  },
  {
    "reviewer": "Jeff V",
    "date": "",
    "stars": 0.5,
    "review": ""
  }
]
```

Here I'm proposing to change the payload by adding some metadata, like including the slug, number of scraped reviews, the page url, then the full scraped reviews. Possibly like this:

```console
$ rotten-reviews doctor_who/s11 3 --tv
{
  "slug": "doctor_who/s11",
  "reviewCount": "3",
  "url": "https://www.rottentomatoes.com/tv/doctor_who/s11/reviews/?page=1&type=user&sort=",
  "reviews": [
    {
      "reviewer": "Frank E.",
      "date": "",
      "stars": 0,
      "review": ""
    },
    {
      "reviewer": "Shannon S",
      "date": "",
      "stars": 5,
      "review": ""
    },
    {
      "reviewer": "Jeff V",
      "date": "",
      "stars": 0.5,
      "review": ""
    }
  ]
}
```

This is possible by just adding another `.then()` after the previous Promise which scrapes the reviews:

```js
.then(reviews => {
  return {
    slug: slug,
    reviewCount: reviewCount,
    url: movieUrl(isTV ? 'tv' : 'm', slug, 1),
    reviews: reviews,
  }
})

```

https://github.com/grikomsn/rotten-reviews/blob/6e3ca0f205933b2dbff9b13cf5c32d2e39dfb095/index.js#L32-L39

You may submit PRs, but I think that it should be discussed further. What do you think about this? 🤔

**Comment by fpereira1** [comment]
For the cli output, I think the tool should be displaying the results in a table format. and have `--json` as an option.  I will create a separate issue for this

**Comment by grikomsn** [comment]
#39
