### ISSUE TITLE
Move 'export to CSV' to main package file

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#15]
Installing `rotten-reviews` package as a global install or running from binaries has the ability to export the reviews to CSV, while in the main package file doesn't include any option.

https://github.com/grikomsn/rotten-reviews/blob/1bcf3fb363baa5a0f3d15bdda3e59f89e2fdd424/bin/rotten-reviews.js#L4

https://github.com/grikomsn/rotten-reviews/blob/1bcf3fb363baa5a0f3d15bdda3e59f89e2fdd424/bin/rotten-reviews.js#L7-L9

https://github.com/grikomsn/rotten-reviews/blob/1bcf3fb363baa5a0f3d15bdda3e59f89e2fdd424/bin/rotten-reviews.js#L23-L28

I'm deciding whether to move the 'export to CSV' part to the main package and change it to a Promise callback after scraping. Or even remove this feature in order to reduce package dependency, who knows.

Further discussion is needed, but do send a PR regarding this issue of you want. ✨

**Comment by fpereira1** [comment]
I would remove it. (or leave it just at the cli)

It would bloat the tool itself to add CSV export. CSV is hardly used in node.

you can pipe the `json2csv` package installed globally to achieve the same thing

**Comment by fpereira1** [comment]
PR https://github.com/grikomsn/rotten-reviews/pull/35

**Comment by fpereira1** [comment]
Merged
