### ISSUE TITLE
Reviews not found after page 51

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#19]
So this is new. I don't know if it's only on my side, but somehow reviews after page 51 returns empty. Links that I've tried:

- https://www.rottentomatoes.com/m/venom_2018/reviews/?page=52&type=user
- https://www.rottentomatoes.com/m/shawshank_redemption/reviews/?page=52&type=user&sort=

If this is intended from Rotten Tomatoes, then that means only 20*51 = 1020 reviews can be scraped. Anyone encountered this, too? 😭

**Comment by andrewfluck** [comment]
I have been encountering this as well, it seems it is an issue from their end. Maybe ask them this question (and not mention that you are scraping data) My guess is that they think it is insane to want to read 1020 reviews
