### ISSUE TITLE
Feature requests and contributions are welcome

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#26]
If you have any thoughts or ideas about `rotten-reviews`, whether recommending a feature or reporting an issue, do send us an issue or, even better, send us a pull request regarding your new feature or bug fixes and we'll be glad to review and merge it.

Hopefully we'll ship version 1.1.0 with many enhancements and fixes. 🎉

**Comment by fpereira1** [comment]
#33, #34 and #37 - they all have PRs associated also

**Comment by fpereira1** [comment]
We should add this to the readme file I think
