### ISSUE TITLE
Integrate progress bar

### ISSUE THREAD

**Issue by fpereira1** [grikomsn/rotten-reviews#34]
The cli tool can take some time to gather results for all the reviews.

It would be nice to add a progress bar to inform the user of the progress

eg. https://www.npmjs.com/package/progress

**Comment by grikomsn** [comment]
@fpereira1 I have invited you to be a repository collaborator, do check your invite: https://github.com/grikomsn/rotten-reviews/invitations

**Comment by fpereira1** [comment]
closing until #43 is implemented
