### ISSUE TITLE
Scrape using number of reviews instead of pages

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#4]
`rotten-reviews` scrapes reviews per page, which per page contains 20 reviews. So if retrieving 500 reviews, that means scraping 25 pages. For some time, I was planning to implement scraping from the number of reviews instead of the number of pages, but I haven't got any idea how.

Any chance anyone would want to work on this feature, do submit a PR or discuss further here. 🎉

**Comment by fpereira1** [comment]
It doesn't seem possible, because the site only displays 20 reviews per page. Looking here: https://www.rottentomatoes.com/m/venom_2018/reviews/?page=3&type=user&sort=
Have you looked into using a rotten tomatoes API?

**Comment by grikomsn** [comment]
I was thinking if the user wants to scrape only 480 reviews, that means still scrapes 25 pages minus 20 reviews. And yes, I know there's an API for Rotten Tomatoes, but I'm taking the scraping approach. 😅

**Comment by fpereira1** [comment]
Ah ok, I get it. Working on a PR for this
