### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by fpereira1** [grikomsn/rotten-reviews#40]
It would be good to have some sort of search for the CLI instead of using an id ie `venom_2018` which is not very user friendly.

Perhaps a better user experience for the CLI would be:

```console
rotten-reviews venom 3
```

User would see a list of search results and could select one of them:

```console
Venom (2005)
Venom (1981)
Venom (2016)
Venom (2013)
Venom (2018)
```

Results are presented as usual

There is a nice JSON api on the website that could be used for this. See https://www.rottentomatoes.com/napi/search/?limit=5&query=venom

**Comment by grikomsn** [comment]
I had the idea of searching, but haven't got the gist on how to search without using the official API. ~~Probably scraping the search results?~~ So I opened DevTools on the search results, and I found this endpoint:

https://www.rottentomatoes.com/api/private/v2.0/search?q=venom&t=movie

And for the choice library would maybe use [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/). Thoughts?

**Comment by fpereira1** [comment]
Yes, Inquirer.js is what I was thinking also

**Comment by grikomsn** [comment]
> Yes, Inquirer.js is what I was thinking also

Since you're also the collaborator, you may merge some PRs if you want 😄

**Comment by andrewfluck** [comment]
See this: #53

**Comment by vimark1** [comment]
Merged
