### ISSUE TITLE
Add Gitter discussion badge

### ISSUE THREAD

**Issue by grikomsn** [grikomsn/rotten-reviews#41]
I made a Gitter lobby for `rotten-reviews`, maybe anyone would want to submit a PR adding a badge on the readme that'd be great.

https://gitter.im/rotten-reviews

**Comment by giuliannosbrugnera** [comment]
I would like to work on this issue, if it is available

**Comment by giuliannosbrugnera** [comment]
Let me know if everything looks good :)
