### ISSUE TITLE
Automate readme updates

### ISSUE THREAD

**Issue by fpereira1** [grikomsn/rotten-reviews#48]
At the moment we have an example in the cli file and the readme.

When something changes in the cli code, we need to manually remember to update the `README.md` file.

We should introduce some automation so that the example is shared, and when it is updated, it gets updated in both, cli help and README.

See: https://www.npmjs.com/package/node-readme

**Comment by grikomsn** [comment]
[The project is archived](https://github.com/revolunet/node-readme). Any other alternatives?
