### ISSUE TITLE
setup Test coverage monitoring & alerting

### ISSUE THREAD

**Issue by fpereira1** [grikomsn/rotten-reviews#51]
https://codecov.io/

**Comment by grikomsn** [comment]
Just installed the integration. Final step is to add `codecov` package as shown here: https://github.com/codecov/example-node

**Comment by fpereira1** [comment]
@grikomsn is there a badge or any other integration we need to do for this?

**Comment by grikomsn** [comment]
Badge added on c3055cd092f09fce3d6c568e5e7b65212e6fc517
