### ISSUE TITLE
Record a demo of the tool for the readme

### ISSUE THREAD

**Issue by vimark1** [grikomsn/rotten-reviews#62]
Record a demo of the tool for the readme like this:

![image](https://camo.githubusercontent.com/6c924cf5740129fbed5e599ec9985cf8a64ce92c/687474703a2f2f7461762e65737069616e732e636f6d2f61736369696e656d612f64656d6f2e676966)

Taken from: https://github.com/tav/asciinema2gif#asciinema2gif

This kind of upfront demo helps devs to understand quickly what the tool does

**Comment by davidsonsns** [comment]
I hope you like @vimark1
